name: Publish to Docker Hub

on:
  push:
    branches:
      - studio
    paths:
      - 'studio/**'
  workflow_dispatch:

jobs:
  publish:
    name: Publish to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64,arm64

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: studio
          platforms: linux/amd64,linux/arm64
          push: true
          tags: supabase/studio:latest
          target: production

  snapshot-tests:
    name:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: studio

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup dependencies
        run: |
          npm run test:snapshots:compose:up
          npm ci

      - name: Run tests
        run: npm run test:snapshots:ci

      - name: Stop infrastructure
        run: npm run test:snapshots:compose:down

      - uses: actions/upload-artifact@v1
        if: ${{ always() }}
        with:
          name: snapshot-test-results
          path: test-results
