name: Snapshot Tests

on:
  pull_request:
    paths:
      - 'studio/tests/snapshot/**'
      - '.github/workflows/snapshot_tests.yml'
      - '.github/workflows/publish_docker_hub.yml'

jobs:
  snapshot-tests:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: studio

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: docker-practice/actions-setup-docker@master

      - name: Setup dependencies
        run: |
          npm run test:snapshots:compose:up
          npm ci
          npx playwright install --with-deps

      - name: Run tests
        run: npm run test:snapshots:ci

      - name: Stop infrastructure
        run: npm run test:snapshots:compose:down

      - uses: actions/upload-artifact@v1
        if: ${{ always() }}
        with:
          name: snapshot-test-results
          path: test-results
