name: Automatically stale issue and PRs
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues
        uses: actions/stale@v9.0.0
        with:
          days-before-pr-stale: 30
          days-before-pr-close: 7
          days-before-issue-stale: 30
          days-before-issue-close: 7
          stale-pr-message: 'This pull request has been inactive for 30 days and will be closed in another week. If you want to give it another month, leave a comment, assign it to someone, or remove a `Stale` label.'
          stale-issue-message: 'This issue has been inactive for 30 days and will be closed in another week. If you want to give it another month, leave a comment, assign it to someone, or remove a `Stale` label.'
          any-of-labels: contributor
          exempt-issue-labels: dnc, needs-analysis
          exempt-pr-labels: dnc
          exempt-all-assignees: true
          exempt-draft-pr: false
